# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kemuri
email: hello@kemurisense.com
description: > # this means to ignore newlines until "baseurl:"
  Kemuri produces wellbeing monitors for elderly people to allow
  safer and happier independent living
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kemurisense.com" # the base hostname & protocol for your site
twitter_username: kemurisense
github_username:  kemurisense

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap