# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kemuri
email: hello@kemuri.io
description: > # this means to ignore newlines until "baseurl:"
  Kemuri produces wellbeing monitors for elderly people to allow
  safer and happier independent living
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kemuri.io" # the base hostname & protocol for your site

# A few parameters for jekyll-seo-tag
lang: en_GB
locale: en_GB
facebook:
  publisher: KemuriSense
logo:  /images/logos/kemuri-logo.png


webmaster_verifications:
  google: Obc0bgbEMdjwcnaOLTG5XozG1XfECB9KlcVRVYZIXFY


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

twitter_username: kemurisense
github_username:  kemurisense

# Build settings
markdown: kramdown

sass:
  style: compressed


# This is config for excluding areas from the jekyll-sitemap plugin
defaults:
  -
    scope:
      path:            "fonts"
    values:
      sitemap:         false